### ISSUE TITLE
Explanation typo error which causes confusion

### ISSUE THREAD

**Issue by devndone** [ayushcshah/ayushcshah.github.io#8]
In your blog http://ayushcshah.github.io/algorithm/binarytree/2016/04/01/detect-duplicate-subtrees.html
there is a place where instead of writing "postorder" you've mentioned "preorder" which causes confusion and makes reader to repeat the read many times to be able to comprehend the logic.
Please correct it. I've marked error word in Bold-Italics-BigFont below:

Background
To check for duplicate subtree tree we first need to uniquely identify each subtrees. A binary tree can be constructed uniquely from a given inorder and postorder traversal reference. With this theory we can represent each subtrees to a unique inorder and postorder traversal pair. Then create a list of inorder and **_### preorder_** traversals of all subtrees and check if there exist pair that repeats in the list.

**Comment by ayushcshah** [comment]
Fixed the typo. Thanks @devndone for the pointing it out.

**Comment by ayushcshah** [comment]
Fixed the typo. Thanks @devndone for the pointing it out.
